# Generated by Django 5.0.7 on 2024-10-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile_image',
            field=models.CharField(default='https://ibb.co.com/xXrms8v'),
        ),
    ]
