# Generated by Django 5.0.7 on 2024-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_date_of_birth_donor_email_donor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
