# Generated by Django 5.0.7 on 2024-07-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donor_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='date_of_birth',
        ),
    ]
