# Generated by Django 5.0.7 on 2024-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_remove_donor_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
