# Generated by Django 5.0.7 on 2024-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donor_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images'),
        ),
    ]
